name: Run Unit Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: ruff lint
        run: |
          ruff check --output-format=github --target-version=py310 .
        continue-on-error: true
      - name: ruff format check
        run: |
          ruff format --check --target-version=py310 .
        continue-on-error: true
      - name: ruff format diff
        run: |
          ruff format --diff --target-version=py310 .
        continue-on-error: true
      - name: pytest databricks functions
        run: |
          coverage run -m pytest  -v -s
      - name: generate pytest coverage report
        run: |
          coverage report -m
      